Keep trailing zeros when displaying Time and Duration
adnanademovic/rosrust pull request #177
Opened 2022-08-25 16:16 UTC by romainreignier

Allow to have nicely aligned logs, like in roscpp

2022-08-29 12:16 UTC, adnanademovic requested changes
Greatly appreciate the effort, and I fully agree with the desired functionality. If you'd return it to the way `display_nanos` worked but without trimming trailing zeros.

I don't want to adjust it myself to take away any of the credit you deserve for the change, but I can if you want me to.

2022-08-29 12:16 UTC, adnanademovic commented on ros_message/src/time.rs
> -    let right = right.trim_end_matches('0');
Wouldn't just removing this line do the same trick?

My concern are perfectly valid but strange payloads, like `Duration { sec: -1, nsec: 1 }` and `Duration { sec: -1, nsec: -1 }` printing the same output in your modification of the code.

2022-08-29 12:16 UTC, adnanademovic commented on ros_message/src/time.rs
> +            self.nsec.abs()
This is the detail I was referencing in the other comment. With sec and nsec being -1, -1 we expect -1.000000001, while with nsec being 1 instead we'd expect -0.999999999.

I guess it's a failure of the test suite that I didn't add this in, as that was the reason for my more complex `display_nanos` function.

2022-08-29 12:16 UTC, adnanademovic commented on ros_message/src/time.rs
> -    let right = right.trim_end_matches('0');
Of course, the if statement below is unnecessary then, as we're always triggering the else case.

2022-08-29 14:15 UTC, romainreignier commented
I have done the requested changes and added a comment to explain the reason of the function.
I hope it's ok for you.

2022-08-30 12:11 UTC, adnanademovic approved these changes

2022-08-30 12:12 UTC, merged

2022-08-30 12:12 UTC, adnanademovic commented
Thanks, this should work well now